### ISSUE TITLE
how to set up a CalDav server

### ISSUE THREAD

**Issue by mabkenar** [dmfs/tasks#148]
Sorry if this question is totally trivial. Could you please tell me where in the app can I enter my ownCloud server credentials to make sync working? I have 'Tasks' installed from f-droid, and all I see is a local 'Task List', with no button to create a CalDav list.

**Comment by jkufner** [comment]
Tasks does not handle CalDAV itself. A connector is used instead. There
are two implementations I know about: one is from DMFS, the author of
Tasks, and second is DavDroid (have not tested it yet). You simply
create account in your phone using one of these two apps and then you
will see tasks from it in Tasks app.

**Comment by mabkenar** [comment]
Thanks for your response. I do use DAVdroid for my calendar and contacts sync. And I see a message "DAVdroid crashed" whenever I hit "refresh" button on the settings of Tasks. But that's all I can see. I think I need to try the other connector that you mentioned. I hope it is also in f-droid.

**Comment by jkufner** [comment]
It is not on F-Droid, because it is not open source (yet... for a few
years).

Report this issue to DavDroid developpers, they may be able to fix it if
you send enough data.

**Comment by dmfs** [comment]
@jkufner You're right, at present it's only partially open source. But we've already released 1000s of lines of open source code during the last years, including some core libraries used by our sync apps and this neat little task app (which consumes a serious amount of our time to develop).

**Comment by jkufner** [comment]
Yes, yes, I'm still looking forward to day when all of it is all open
source. And thank you for Tasks app, it is awesome and I use it almost
every day.

**Comment by mabkenar** [comment]
I just found this from the developer of DAVdroid:
https://github.com/bitfireAT/davdroid/issues/552#issuecomment-112104592
I did re-install DAVdroid, I re-entered user/pass for both of my ownCloud accounts, and now I can see list my CalDAV tasks :) I still don't see my recently added tasks, but I hope it is because the slow sync process.

But are such glitches bugs? Or fundamental shortcomings of Android with online accounts? I have seen similar incompatibility problems between K-9 Mail client and APG/OpenKeychain key management apps. Why is this?

**Comment by dmfs** [comment]
@mabkenar This is an issue with permissions in Android. Android only grants permissions that were known at the time an app was installed. If you installed DAVdroid before you installed the Task app, Android doesn't grant permissions to access tasks to DAVdroid.
AFAIK that will change in Android M.
